### ISSUE TITLE
Issue creating a `Retained<NSView>` from `NonNull<c_void>`

### ISSUE THREAD

**Issue by kanerogers** [madsmtm/objc2#703]
Hi there!

In `objc2` version `0.5.2` I could construct a `Retained<NSView>` from a pointer obtained using `raw_window_handle`, ie:

```rust
match window.window_handle().unwrap().as_raw() {
        raw_window_handle::RawWindowHandle::AppKit(handle) => {
            let ns_view = handle.ns_view.as_ptr();
            let ns_view: Retained<NSView> = unsafe { Retained::retain(ns_view as *mut _) }.unwrap();
        }
        _ => {},
}
```

However this no longer works in `0.6.0` as `NSView` does not implement the `Message` trait as required on the bounds on `Retained::retain`.

What should I be doing now instead?

Thanks!

**Comment by madsmtm** [comment]
The problem is that `objc2-app-kit` v0.3 has yet to be released, see https://github.com/madsmtm/objc2/pull/700.

**Comment by madsmtm** [comment]
`objc2-app-kit` v0.3 has now been released

**Comment by kanerogers** [comment]
Thanks so much for the lightning fast response! I was trying to fetch the dependency for `objc2-app-kit` using git, but I guess if I was fetching the others from crates.io that would still cause a mismatch. 🤦‍♀ 

Thanks again! This crate is absolutely, amazing, and 0.3.0 seems like another step in the right direction.
